"""add User.plaid_sync_cursor

Revision ID: 250dac683643
Revises: 69650ded897a
Create Date: 2026-08-26 16:04:50.424003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250dac683643'
down_revision = '69650ded897a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_sync_cursor', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plaid_sync_cursor')

    # ### end Alembic commands ###
