"""rename simplefin columns to plaid, add plaid_item_id and account unique constraint

Revision ID: 69650ded897a
Revises: acb3adc92f72
Create Date: 2026-08-26 15:41:14.894173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69650ded897a'
down_revision = 'acb3adc92f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_account_id', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_account_user_plaid_id', ['user_id', 'plaid_account_id'])
        batch_op.drop_column('simplefin_account_id')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_transaction_id', sa.String(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_transaction_account_simplefin_id'), type_='unique')
        batch_op.create_unique_constraint('uq_transaction_account_plaid_id', ['account_id', 'plaid_transaction_id'])
        batch_op.drop_column('simplefin_transaction_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_access_token_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('plaid_item_id', sa.String(length=120), nullable=True))
        batch_op.drop_column('simplefin_access_url_encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simplefin_access_url_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('plaid_item_id')
        batch_op.drop_column('plaid_access_token_encrypted')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simplefin_transaction_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_transaction_account_plaid_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_transaction_account_simplefin_id'), ['account_id', 'simplefin_transaction_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('plaid_transaction_id')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simplefin_account_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_account_user_plaid_id', type_='unique')
        batch_op.drop_column('plaid_account_id')

    # ### end Alembic commands ###
