"""add transaction is_income

Revision ID: a1b2c3d4e5f6
Revises: e6875d83ae67
Create Date: 2026-08-26 21:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'e6875d83ae67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        # server_default so the NOT NULL add succeeds against tables with
        # existing rows; dropped immediately after — the app-level default
        # (models.py) is the source of truth going forward.
        batch_op.add_column(
            sa.Column('is_income', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.alter_column('is_income', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('is_income')

    # ### end Alembic commands ###
