"""add category archived

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-08-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        # server_default so the NOT NULL add succeeds against tables with
        # existing rows; dropped immediately after — the app-level default
        # (models.py) is the source of truth going forward.
        batch_op.add_column(
            sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.alter_column('archived', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
